# Question 1

In [3]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([5.5,6.5,7.5,8.5])
print("Addition:")
print(np.add(x,y))
print("Subtraction:")
print(np.subtract(x,y))
print("Multiplication:")
print(np.multiply(x,y))
print("Division:")
print(np.divide(x,y))

Addition:
[ 6.5  8.5 10.5 12.5]
Subtraction:
[-4.5 -4.5 -4.5 -4.5]
Multiplication:
[ 5.5 13.  22.5 34. ]
Division:
[0.18181818 0.30769231 0.4        0.47058824]


# Question 2

In [14]:
X=np.array([[1,2],[3,4]])
p=np.sqrt(X)# for square root of the given array
print("Square root of array:\n",p)

Square root of array:
 [[1.         1.41421356]
 [1.73205081 2.        ]]


In [9]:
max_column=X.max(axis=0)#for max element in column..
print("maximum elements column wise:",max_column)
min_column=X.min(axis=0)#for min element in coulmn..
print("minimum elements column wise:",min_column)

maximum elements column wise: [3 4]
minimum elements column wise: [1 2]


In [11]:
max_row=X.max(axis=1)#for max element in row..
print("maximum elements row wise:",max_row)
min_row=X.min(axis=1)#for min element in row..
print("minimum elements row wise:",min_row)

maximum elements row wise: [2 4]
minimum elements row wise: [1 3]


In [18]:
median=np.median(X)#for median
print("Median:",median)
std_dev=X.std()#for standard deviation
print("Standard Deviation:",std_dev)
mean=X.mean()#for mean
print("Mean:",mean)
exponent=np.exp(X)#for exponent...
print("Exponentiation of array:\n",exponent)

Median: 2.5
Standard Deviation: 1.118033988749895
Mean: 2.5
Exponentiation of array:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
